### ISSUE TITLE
Ability to compose and send mass emails from Mission Control

### ISSUE THREAD

**Issue by k7hpn** [MCLD/greatreadingadventure#567]
Job functionality is in place to send the emails, but the following need to be completed:

- [ ] ~~Ability to create emails (possibly with MJML)~~
- [x] Ability to send test emails (#598)
- [x] Ability to kick off job sending email to subscribed participants (#598)
- [ ] Ability to kick off job sending emails to subscribers who haven't joined (from emails collected before the program started or after the program ended) (#601)
